kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-hosts-converter
rules:
- apiGroups:
  - ""
  resources: 
  - "events"
  - "nodes"
  verbs: 
  - "watch"
  - "list"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: node-hosts-converter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-hosts-converter
subjects:
  - kind: User
    name: node-hosts-converter
    apiGroup: rbac.authorization.k8s.io
